from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


plugin = Path("src/obs-plugin/plugin.cpp")
text = plugin.read_text(encoding="utf-8")

text = replace_once(
    text,
    'constexpr const char* kPluginPath = "vst3_path";\nconstexpr const char* kCustomPath = "custom_vst3_path";\n',
    'constexpr const char* kSourceMode = "vst3_source_mode";\nconstexpr const char* kSourceInstalled = "installed";\nconstexpr const char* kSourceBrowse = "browse";\nconstexpr const char* kPluginPath = "vst3_path";\nconstexpr const char* kCustomPath = "custom_vst3_path";\n',
    "source-mode constants",
)

text = replace_once(
    text,
    '    obs_property_list_add_string(list, obs_module_text("UseBrowseVST3"), "");\n',
    '    obs_property_list_add_string(list, obs_module_text("SelectInstalledVST3"), "");\n',
    "installed-list placeholder",
)

marker = '''std::pair<std::string, std::string> current_identity(Filter* filter)\n{\n    if (!filter)\n        return {};\n    std::lock_guard lock(filter->config_mutex);\n    return {filter->path, filter->class_id};\n}\n'''
insert = '''enum class Vst3SourceMode {\n    Installed,\n    Browse,\n};\n\nVst3SourceMode source_mode_from_settings(obs_data_t* settings)\n{\n    if (!settings)\n        return Vst3SourceMode::Installed;\n\n    if (obs_data_has_user_value(settings, kSourceMode)) {\n        const std::string mode = obs_data_get_string(settings, kSourceMode);\n        return mode == kSourceBrowse ? Vst3SourceMode::Browse : Vst3SourceMode::Installed;\n    }\n\n    // Backward-compatible migration for scenes saved before the explicit\n    // source selector existed. A custom-only scene keeps working as Browse;\n    // otherwise the installed list remains the default.\n    const std::string selected = obs_data_get_string(settings, kPluginPath);\n    const std::string custom = obs_data_get_string(settings, kCustomPath);\n    return !custom.empty() && selected.empty()\n               ? Vst3SourceMode::Browse\n               : Vst3SourceMode::Installed;\n}\n\nstd::pair<std::string, std::string> current_identity(Filter* filter)\n{\n    if (!filter)\n        return {};\n    std::lock_guard lock(filter->config_mutex);\n    return {filter->path, filter->class_id};\n}\n'''
text = replace_once(text, marker, insert, "source-mode helper")

text = replace_once(
    text,
    '    obs_data_set_default_bool(settings, kEnabled, true);\n    obs_data_set_default_string(settings, kCustomPath, "");\n',
    '    obs_data_set_default_bool(settings, kEnabled, true);\n    obs_data_set_default_string(settings, kSourceMode, kSourceInstalled);\n    obs_data_set_default_string(settings, kCustomPath, "");\n',
    "source-mode default",
)

old_selection = '''    const std::string selected = obs_data_get_string(settings, kPluginPath);\n    const std::string custom = obs_data_get_string(settings, kCustomPath);\n    const std::string legacy_class = obs_data_get_string(settings, kClassId);\n\n    std::string path;\n    std::string class_id;\n    split_selection(selected, path, class_id);\n    if (path.empty() && !custom.empty()) {\n        path = custom;\n        class_id = legacy_class;\n    } else if (class_id.empty()) {\n        class_id = legacy_class;\n    }\n'''
new_selection = '''    const Vst3SourceMode source_mode = source_mode_from_settings(settings);\n    const std::string selected = obs_data_get_string(settings, kPluginPath);\n    const std::string custom = obs_data_get_string(settings, kCustomPath);\n    const std::string legacy_class = obs_data_get_string(settings, kClassId);\n\n    std::string path;\n    std::string class_id;\n    if (source_mode == Vst3SourceMode::Installed) {\n        split_selection(selected, path, class_id);\n        if (class_id.empty())\n            class_id = legacy_class;\n    } else {\n        path = custom;\n        // Preserve legacy manually-browsed scenes that stored an explicit\n        // class id. New manual Browse selections normally keep this empty and\n        // let the isolated host choose the bundle's audio-effect class.\n        class_id = legacy_class;\n    }\n'''
text = replace_once(text, old_selection, new_selection, "active source selection")

old_callback = '''bool identity_property_modified(void* data, obs_properties_t* props, obs_property_t* property, obs_data_t* settings)\n{\n    auto* filter = static_cast<Filter*>(data);\n    if (!filter || !settings || filter->shutting_down.load(std::memory_order_acquire))\n        return false;\n\n    // Keep exactly one identity source active. A custom Browse gesture must\n    // override a previous installed-list selection immediately, and selecting\n    // from the installed list must clear a previous custom bundle. Otherwise\n    // filter_update() cannot know which of two non-empty settings the user just\n    // changed and the stale installed-list value wins.\n    const std::string changed_property = property ? obs_property_name(property) : "";\n    if (changed_property == kPluginPath) {\n        obs_data_set_string(settings, kCustomPath, "");\n    } else if (changed_property == kCustomPath) {\n        obs_data_set_string(settings, kPluginPath, "");\n        obs_data_set_string(settings, kClassId, "");\n    }\n\n    // Load/restart the isolated helper synchronously for this explicit user\n    // identity change. Do not call obs_source_update_properties() here: the\n    // OBS Qt view is still handling the current WidgetInfo/property pointer.\n    filter_update(filter, settings);\n\n    // Native OBS VST keeps its editor button in the same properties object and\n    // only toggles visibility from the modified callback. Do the same here so\n    // the Open Plug-in Interface button becomes available in the already-open\n    // Filters window as soon as the helper is ready, without closing/reopening\n    // Properties and without rebuilding the view from inside ControlChanged().\n    if (props) {\n        if (auto* open_editor = obs_properties_get(props, kOpenEditor)) {\n            const bool ready = bridge_running(filter);\n            obs_property_set_visible(open_editor, ready);\n            obs_property_set_enabled(open_editor, ready);\n        }\n    }\n    return true;\n}\n'''
new_callback = '''void update_editor_button(obs_properties_t* props, Filter* filter)\n{\n    if (!props)\n        return;\n    if (auto* open_editor = obs_properties_get(props, kOpenEditor)) {\n        const bool ready = filter && bridge_running(filter);\n        obs_property_set_visible(open_editor, ready);\n        obs_property_set_enabled(open_editor, ready);\n    }\n}\n\nvoid update_source_mode_visibility(obs_properties_t* props, Vst3SourceMode mode)\n{\n    if (!props)\n        return;\n    const bool installed = mode == Vst3SourceMode::Installed;\n    if (auto* list = obs_properties_get(props, kPluginPath))\n        obs_property_set_visible(list, installed);\n    if (auto* rescan = obs_properties_get(props, kRescan))\n        obs_property_set_visible(rescan, installed);\n    if (auto* browse = obs_properties_get(props, kCustomPath))\n        obs_property_set_visible(browse, !installed);\n}\n\nbool identity_property_modified(void* data, obs_properties_t* props, obs_property_t* property, obs_data_t* settings)\n{\n    auto* filter = static_cast<Filter*>(data);\n    if (!filter || !settings || filter->shutting_down.load(std::memory_order_acquire))\n        return false;\n\n    const Vst3SourceMode mode = source_mode_from_settings(settings);\n    const std::string changed_property = property ? obs_property_name(property) : "";\n    if ((changed_property == kPluginPath && mode != Vst3SourceMode::Installed) ||\n        (changed_property == kCustomPath && mode != Vst3SourceMode::Browse))\n        return false;\n\n    // The helper is started synchronously for the explicit user selection.\n    // The editor button already belongs to this same properties object, so we\n    // only toggle its state; no source-wide property-tree rebuild is required.\n    filter_update(filter, settings);\n    update_editor_button(props, filter);\n    return true;\n}\n\nbool source_mode_modified(void* data, obs_properties_t* props, obs_property_t*, obs_data_t* settings)\n{\n    auto* filter = static_cast<Filter*>(data);\n    if (!filter || !settings || filter->shutting_down.load(std::memory_order_acquire))\n        return false;\n\n    const Vst3SourceMode mode = source_mode_from_settings(settings);\n    update_source_mode_visibility(props, mode);\n\n    // Switching source mode immediately activates the value retained for that\n    // mode. The inactive source is ignored rather than erased, so toggling back\n    // restores the user's previous installed/manual choice without ambiguity.\n    filter_update(filter, settings);\n    update_editor_button(props, filter);\n    return true;\n}\n'''
text = replace_once(text, old_callback, new_callback, "property callbacks")

old_properties = '''    auto* list = obs_properties_add_list(props, kPluginPath, obs_module_text("InstalledVST3"),\n                                         OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_STRING);\n    populate_plugin_list(list);\n    if (filter)\n        obs_property_set_modified_callback2(list, identity_property_modified, filter);\n    obs_properties_add_button(props, kRescan, obs_module_text("RescanVST3"), rescan_button);\n    auto* custom_path = obs_properties_add_path(\n        props, kCustomPath, obs_module_text("CustomVST3Path"), OBS_PATH_DIRECTORY, nullptr, nullptr);\n    if (filter)\n        obs_property_set_modified_callback2(custom_path, identity_property_modified, filter);\n\n    // Match the native OBS VST workflow: keep the editor button in the\n    // properties object from the beginning and reveal it only when a plug-in\n    // is actually loaded. This is intentionally the only normal plug-in\n    // control surface exposed in OBS; vendor parameters belong in the vendor\n    // editor, not as a wall of generic sliders in the Filters dialog.\n    auto* open_editor = obs_properties_add_button2(\n        props, kOpenEditor, obs_module_text("OpenPluginUI"), open_editor_button, filter);\n\n    bool running = false;\n    if (filter && !filter->shutting_down.load(std::memory_order_acquire)) {\n        const auto [path, class_id] = current_identity(filter);\n        if (!path.empty()) {\n            std::lock_guard restart_lock(filter->restart_mutex);\n            running = filter->bridge_owner && filter->bridge_owner->running() &&\n                      filter->bridge_path == path && filter->bridge_class_id == class_id;\n        }\n    }\n\n    obs_property_set_visible(open_editor, running);\n    obs_property_set_enabled(open_editor, running);\n    return props;\n'''
new_properties = '''    auto* source_mode = obs_properties_add_list(\n        props, kSourceMode, obs_module_text("VST3Source"),\n        OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_STRING);\n    obs_property_list_add_string(source_mode, obs_module_text("VST3SourceInstalled"), kSourceInstalled);\n    obs_property_list_add_string(source_mode, obs_module_text("VST3SourceBrowse"), kSourceBrowse);\n    if (filter)\n        obs_property_set_modified_callback2(source_mode, source_mode_modified, filter);\n\n    auto* list = obs_properties_add_list(props, kPluginPath, obs_module_text("InstalledVST3"),\n                                         OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_STRING);\n    populate_plugin_list(list);\n    if (filter)\n        obs_property_set_modified_callback2(list, identity_property_modified, filter);\n    obs_properties_add_button(props, kRescan, obs_module_text("RescanVST3"), rescan_button);\n    auto* custom_path = obs_properties_add_path(\n        props, kCustomPath, obs_module_text("CustomVST3Path"), OBS_PATH_DIRECTORY, nullptr, nullptr);\n    if (filter)\n        obs_property_set_modified_callback2(custom_path, identity_property_modified, filter);\n\n    // Native-like user-facing surface: the vendor editor is the normal control\n    // surface. Generic VST3 parameter fallback remains an internal recovery\n    // capability and is intentionally not rendered as hundreds of OBS sliders.\n    obs_properties_add_button2(\n        props, kOpenEditor, obs_module_text("OpenPluginUI"), open_editor_button, filter);\n\n    Vst3SourceMode mode = Vst3SourceMode::Installed;\n    if (filter && filter->context) {\n        if (obs_data_t* settings = obs_source_get_settings(filter->context)) {\n            mode = source_mode_from_settings(settings);\n            obs_data_release(settings);\n        }\n    }\n    update_source_mode_visibility(props, mode);\n    update_editor_button(props, filter);\n    return props;\n'''
text = replace_once(text, old_properties, new_properties, "properties layout")

text = text.replace(
    'return "Crash-isolated VST3 host with OBS-native workflow, vendor interface and fallback controls";',
    'return "Crash-isolated VST3 host with OBS-native source selection and vendor interface";',
)
plugin.write_text(text, encoding="utf-8")

locale = Path("data/locale/en-US.ini")
loc = locale.read_text(encoding="utf-8")
loc = replace_once(
    loc,
    'InstalledVST3="Installed VST 3 Plug-in"\nUseBrowseVST3="Browse / Custom VST3…"\n',
    'VST3Source="VST3 Source"\nVST3SourceInstalled="Installed plug-ins"\nVST3SourceBrowse="Browse manually"\nInstalledVST3="Plug-in"\nSelectInstalledVST3="Select a VST3 plug-in"\n',
    "locale source selector",
)
loc = loc.replace('CustomVST3Path="Browse / Custom VST3"', 'CustomVST3Path="VST3 bundle"')
loc = loc.replace('NoPluginsScanned="No installed VST3 plug-ins found — use Browse below"', 'NoPluginsScanned="No installed VST3 plug-ins found"')
locale.write_text(loc, encoding="utf-8")

guard = Path("tests/obs_properties_ownership.cmake")
g = guard.read_text(encoding="utf-8")
needle = 'message(STATUS "OBS Properties ownership guard passed")\n'
extra = '''# User-facing Single Host UX is intentionally mutually exclusive: users choose\n# an installed plug-in OR manual Browse. Generic parameter walls are not part\n# of the normal OBS filter surface.\nforeach(REQUIRED_TOKEN\n        "kSourceMode"\n        "kSourceInstalled"\n        "kSourceBrowse"\n        "source_mode_modified"\n        "update_source_mode_visibility")\n    string(FIND "${SOURCE_TEXT}" "${REQUIRED_TOKEN}" TOKEN_POS)\n    if(TOKEN_POS EQUAL -1)\n        message(FATAL_ERROR "Simple VST3 source-mode UX contract missing: ${REQUIRED_TOKEN}")\n    endif()\nendforeach()\n\nstring(FIND "${SOURCE_TEXT}" "add_generic_parameter_properties(" FALLBACK_UI_POS)\nif(NOT FALLBACK_UI_POS EQUAL -1)\n    message(FATAL_ERROR\n        "Generic VST3 fallback parameter wall must not be rendered in the normal OBS Properties UI.")\nendif()\n\nmessage(STATUS "OBS Properties ownership and simple UX guards passed")\n'''
g = replace_once(g, needle, extra, "UX guard")
guard.write_text(g, encoding="utf-8")
