file(READ "${RACK_PROTOCOL}" PROTOCOL_TEXT)
file(READ "${RACK_SOURCE}" SOURCE_TEXT)

string(FIND "${PROTOCOL_TEXT}" "#include \"common/protocol.hpp\"" SINGLE_PROTOCOL_INCLUDE)
if(NOT SINGLE_PROTOCOL_INCLUDE EQUAL -1)
    message(FATAL_ERROR "Rack protocol must remain independent from Single common/protocol.hpp")
endif()
# R1-3 introduced the independently versioned immutable-topology contract at
# v3. Later Rack tickets may extend that binary layout; the enduring R1-3
# invariant is therefore v3-or-newer, not a forever-frozen literal v3.
if(NOT PROTOCOL_TEXT MATCHES "kRackProtocolVersion = ([3-9]|[1-9][0-9]+)")
    message(FATAL_ERROR "R1-3 topology transport requires independent Rack protocol v3 or newer")
endif()
if(NOT PROTOCOL_TEXT MATCHES "using RackSlotId = std::uint64_t")
    message(FATAL_ERROR "R1-3 requires stable slot identity independent of order")
endif()
if(NOT PROTOCOL_TEXT MATCHES "topology_request_generation")
    message(FATAL_ERROR "R1-3 requires bounded topology request generation")
endif()
if(NOT PROTOCOL_TEXT MATCHES "topology_response_generation")
    message(FATAL_ERROR "R1-3 requires topology acknowledgement generation")
endif()
if(NOT PROTOCOL_TEXT MATCHES "committed_chain_generation")
    message(FATAL_ERROR "R1-3 must publish coherent committed Rack generation")
endif()
if(NOT PROTOCOL_TEXT MATCHES "processed_chain_generation")
    message(FATAL_ERROR "R1-3 audio response must identify the immutable generation it processed")
endif()
if(NOT PROTOCOL_TEXT MATCHES "committed_slot_ids")
    message(FATAL_ERROR "R1-3 must publish stable IDs in committed order")
endif()

if(NOT SOURCE_TEXT MATCHES "struct RackChainGeneration")
    message(FATAL_ERROR "R1-3 helper must own immutable RackChainGeneration snapshots")
endif()
if(NOT SOURCE_TEXT MATCHES "std::atomic")
    message(FATAL_ERROR "R1-3 generation publication/read reachability must use atomics")
endif()
if(NOT SOURCE_TEXT MATCHES "reader")
    message(FATAL_ERROR "R1-3 must retain old generation storage while DSP readers can reach it")
endif()
if(NOT SOURCE_TEXT MATCHES "control_loop")
    message(FATAL_ERROR "R1-3 topology lifecycle/mutation must run on a control path separate from DSP")
endif()
if(NOT SOURCE_TEXT MATCHES "plugin_c.open")
    message(FATAL_ERROR "R1-3 Add C must load the new HostedPlugin off DSP")
endif()
if(NOT SOURCE_TEXT MATCHES "processed_chain_generation")
    message(FATAL_ERROR "R1-3 DSP must publish the exact generation used by the block")
endif()

foreach(FORBIDDEN "std::mutex" "std::lock_guard" "std::unique_lock")
    string(FIND "${SOURCE_TEXT}" "${FORBIDDEN}" FOUND_TOKEN)
    if(NOT FOUND_TOKEN EQUAL -1)
        message(FATAL_ERROR "Rack source must not add control mutex dependency to normal DSP: ${FORBIDDEN}")
    endif()
endforeach()

foreach(FORBIDDEN "std::vector" "std::make_unique" "std::make_shared" "new " "malloc(" "calloc(" "realloc(")
    string(FIND "${SOURCE_TEXT}" "${FORBIDDEN}" FOUND_TOKEN)
    if(NOT FOUND_TOKEN EQUAL -1)
        message(FATAL_ERROR "project-owned allocation token '${FORBIDDEN}' found in Rack source")
    endif()
endforeach()

message(STATUS "R1-3 immutable topology generation source contract passed")
