if(NOT DEFINED SOURCE_FILE)
  message(FATAL_ERROR "SOURCE_FILE is required")
endif()

file(READ "${SOURCE_FILE}" SOURCE)

string(REGEX MATCHALL "getProcessContextRequirements\\(" REQUIREMENT_CALLS "${SOURCE}")
list(LENGTH REQUIREMENT_CALLS REQUIREMENT_CALL_COUNT)
if(NOT REQUIREMENT_CALL_COUNT EQUAL 1)
  message(FATAL_ERROR "VST3 host must query getProcessContextRequirements exactly once in Vst3Engine::open; found ${REQUIREMENT_CALL_COUNT}")
endif()

string(FIND "${SOURCE}" "processor_->setupProcessing(process_setup_)" SETUP_POS)
string(FIND "${SOURCE}" "getProcessContextRequirements()" REQUIREMENTS_POS)
string(FIND "${SOURCE}" "component_->setActive(true)" ACTIVE_POS)
if(SETUP_POS LESS 0 OR REQUIREMENTS_POS LESS 0 OR ACTIVE_POS LESS 0)
  message(FATAL_ERROR "Could not find setup/requirements/activation lifecycle markers")
endif()
if(NOT (SETUP_POS LESS REQUIREMENTS_POS AND REQUIREMENTS_POS LESS ACTIVE_POS))
  message(FATAL_ERROR "Process-context requirements query must occur after setupProcessing and before first setActive(true)")
endif()

string(REGEX MATCHALL "make_process_context_frame\\(" FRAME_CALLS "${SOURCE}")
list(LENGTH FRAME_CALLS FRAME_CALL_COUNT)
if(NOT FRAME_CALL_COUNT EQUAL 2)
  message(FATAL_ERROR "Expected exactly two process-context frame construction sites (initial + audio block); found ${FRAME_CALL_COUNT}")
endif()

string(FIND "${SOURCE}" "const auto context_frame = make_process_context_frame(" BLOCK_FRAME_POS)
string(FIND "${SOURCE}" "processor_->process(process_data_)" PROCESS_POS)
string(FIND "${SOURCE}" "sample_position_ += slot.frames" ADVANCE_POS)
if(BLOCK_FRAME_POS LESS 0 OR PROCESS_POS LESS 0 OR ADVANCE_POS LESS 0)
  message(FATAL_ERROR "Could not find deterministic audio-block process-context markers")
endif()
if(NOT (BLOCK_FRAME_POS LESS PROCESS_POS AND PROCESS_POS LESS ADVANCE_POS))
  message(FATAL_ERROR "Audio-block context must be prepared before process() and sample position advanced only after successful process()")
endif()

string(FIND "${SOURCE}" "bool Vst3Engine::flush_parameter_changes() noexcept" FLUSH_BEGIN)
string(FIND "${SOURCE}" "bool Vst3Engine::process(AudioSlot& slot) noexcept" PROCESS_BEGIN)
if(FLUSH_BEGIN LESS 0 OR PROCESS_BEGIN LESS 0 OR NOT FLUSH_BEGIN LESS PROCESS_BEGIN)
  message(FATAL_ERROR "Could not isolate zero-sample parameter flush implementation")
endif()
math(EXPR FLUSH_LENGTH "${PROCESS_BEGIN} - ${FLUSH_BEGIN}")
string(SUBSTRING "${SOURCE}" ${FLUSH_BEGIN} ${FLUSH_LENGTH} FLUSH_SOURCE)
string(FIND "${FLUSH_SOURCE}" "sample_position_" FLUSH_SAMPLE_POSITION)
if(NOT FLUSH_SAMPLE_POSITION EQUAL -1)
  message(FATAL_ERROR "Zero-sample parameter flush must never advance or rewrite project/continuous sample time")
endif()

# S1.6 full reload must recreate through Vst3Engine::open(), because open() is
# the lifecycle frontier that performs the one-per-instance requirements query.
get_filename_component(HOST_DIR "${SOURCE_FILE}" DIRECTORY)
set(HOST_MAIN_FILE "${HOST_DIR}/main.cpp")
if(NOT EXISTS "${HOST_MAIN_FILE}")
  message(FATAL_ERROR "Could not locate host main.cpp for reload/re-query contract")
endif()
file(READ "${HOST_MAIN_FILE}" HOST_MAIN_SOURCE)
string(FIND "${HOST_MAIN_SOURCE}" "bool reload_recreate_plugin() noexcept override" RELOAD_BEGIN)
string(FIND "${HOST_MAIN_SOURCE}" "bool reload_restore_state() noexcept override" RELOAD_END)
if(RELOAD_BEGIN LESS 0 OR RELOAD_END LESS 0 OR NOT RELOAD_BEGIN LESS RELOAD_END)
  message(FATAL_ERROR "Could not isolate full reload recreation frontier")
endif()
math(EXPR RELOAD_LENGTH "${RELOAD_END} - ${RELOAD_BEGIN}")
string(SUBSTRING "${HOST_MAIN_SOURCE}" ${RELOAD_BEGIN} ${RELOAD_LENGTH} RELOAD_SOURCE)
string(FIND "${RELOAD_SOURCE}" "engine_.close();" RELOAD_CLOSE_POS)
string(FIND "${RELOAD_SOURCE}" "engine_.open(" RELOAD_OPEN_POS)
if(RELOAD_CLOSE_POS LESS 0 OR RELOAD_OPEN_POS LESS 0 OR NOT RELOAD_CLOSE_POS LESS RELOAD_OPEN_POS)
  message(FATAL_ERROR "Full kReloadComponent recreation must close then reopen through Vst3Engine::open so requirements are freshly queried")
endif()

message(STATUS "VST3 process-context source contract ok")
