set(PLUGIN_SOURCE "${ROOT}/src/obs-plugin/plugin.cpp")
set(RACK_FILTER_SOURCE "${ROOT}/src/obs-plugin/rack_filter.cpp")
set(ROOT_CMAKE "${ROOT}/CMakeLists.txt")
set(INSTALLER "${ROOT}/installer/windows/obs-safe-vst3.iss")
set(LOCALE "${ROOT}/data/locale/en-US.ini")

foreach(REQUIRED IN ITEMS "${PLUGIN_SOURCE}" "${ROOT_CMAKE}" "${INSTALLER}" "${LOCALE}")
    if(NOT EXISTS "${REQUIRED}")
        message(FATAL_ERROR "R3-1 required source missing: ${REQUIRED}")
    endif()
endforeach()
if(NOT EXISTS "${RACK_FILTER_SOURCE}")
    message(FATAL_ERROR "R3-1 production OBS Rack filter source does not exist")
endif()

file(READ "${PLUGIN_SOURCE}" PLUGIN)
file(READ "${RACK_FILTER_SOURCE}" RACK_FILTER)
file(READ "${ROOT_CMAKE}" CMAKE_TEXT)
file(READ "${INSTALLER}" INSTALLER_TEXT)
file(READ "${LOCALE}" LOCALE_TEXT)

if(NOT PLUGIN MATCHES "obs_safe_vst3_filter")
    message(FATAL_ERROR "R3-1 must preserve the existing Single internal filter ID")
endif()
if(PLUGIN MATCHES "obs_safe_vst3_filter[^\n]*rack" OR PLUGIN MATCHES "rack[^\n]*obs_safe_vst3_filter")
    message(FATAL_ERROR "R3-1 must not repurpose the Single internal ID for Rack")
endif()
if(NOT RACK_FILTER MATCHES "obs_safe_vst3_rack_filter")
    message(FATAL_ERROR "R3-1 must freeze a distinct Rack internal filter ID")
endif()
if(NOT PLUGIN MATCHES "obs_register_source\\(&source_info\\)" OR
   NOT PLUGIN MATCHES "obs_register_source\\(&rack_source_info\\)")
    message(FATAL_ERROR "obs_module_load must register both Single and Rack source infos")
endif()
if(NOT RACK_FILTER MATCHES "OBS_SOURCE_TYPE_FILTER" OR NOT RACK_FILTER MATCHES "OBS_SOURCE_AUDIO")
    message(FATAL_ERROR "VST3 Rack must register as an OBS audio filter")
endif()
if(NOT RACK_FILTER MATCHES "obs_properties_create" OR
   NOT RACK_FILTER MATCHES "obs_properties_add_button2" OR
   NOT RACK_FILTER MATCHES "RackOpen")
    message(FATAL_ERROR "R3-1 Rack Properties must be a public thin Open Rack launcher/status surface")
endif()
foreach(FORBIDDEN IN ITEMS "QWidget" "QObject" "Qt6::" "ImGui" "D3D11" "InstalledVST3" "RescanVST3" "CustomVST3Path")
    if(RACK_FILTER MATCHES "${FORBIDDEN}")
        message(FATAL_ERROR "R3-1 Rack OBS adapter leaked out-of-scope/private UI dependency: ${FORBIDDEN}")
    endif()
endforeach()
if(NOT CMAKE_TEXT MATCHES "src/obs-plugin/rack_filter.cpp" OR
   NOT CMAKE_TEXT MATCHES "src/platform/windows/win_rack_bridge.cpp")
    message(FATAL_ERROR "normal OBS module build must compile the Rack OBS adapter and parent-side Rack bridge")
endif()
if(NOT CMAKE_TEXT MATCHES "obs-safe-vst3-rack-host")
    message(FATAL_ERROR "normal Windows build/package must include the Rack helper executable")
endif()
if(CMAKE_TEXT MATCHES "target_link_libraries\\(obs-safe-vst3[^\n]*safevst3_rack_imgui")
    message(FATAL_ERROR "Dear ImGui must never be linked into the OBS module")
endif()
if(NOT INSTALLER_TEXT MATCHES "obs-safe-vst3-rack-host.exe")
    message(FATAL_ERROR "Windows installer must install/clean the Rack helper")
endif()
if(NOT LOCALE_TEXT MATCHES "SafeVST3RackFilter" OR
   NOT LOCALE_TEXT MATCHES "RackOpen" OR
   NOT LOCALE_TEXT MATCHES "RackStatus")
    message(FATAL_ERROR "R3-1 must provide normal-user Rack filter/launcher/status strings")
endif()

message(STATUS "R3-1 separate OBS Rack launcher/status source contract passed")
