if(NOT DEFINED HEADER OR NOT EXISTS "${HEADER}")
    message(FATAL_ERROR "R0-2 HostedPlugin header is missing")
endif()
if(NOT DEFINED SOURCE OR NOT EXISTS "${SOURCE}")
    message(FATAL_ERROR "R0-2 HostedPlugin source is missing")
endif()

file(READ "${HEADER}" header_source)
file(READ "${SOURCE}" implementation_source)

foreach(forbidden IN ITEMS "AudioSlot" "SharedAudioRegion" "common/protocol.hpp" "Vst3Engine")
    string(FIND "${header_source}" "${forbidden}" header_position)
    if(NOT header_position EQUAL -1)
        message(FATAL_ERROR "HostedPlugin public seam must remain protocol-neutral; header contains forbidden token: ${forbidden}")
    endif()
    string(FIND "${implementation_source}" "${forbidden}" source_position)
    if(NOT source_position EQUAL -1)
        message(FATAL_ERROR "HostedPlugin deep implementation must remain outside Single transport; source contains forbidden token: ${forbidden}")
    endif()
endforeach()

string(FIND "${header_source}" "class HostedPlugin" class_position)
if(class_position EQUAL -1)
    message(FATAL_ERROR "HostedPlugin public seam must declare class HostedPlugin")
endif()
string(FIND "${header_source}" "ProcessBlockView" process_view_position)
if(process_view_position EQUAL -1)
    message(FATAL_ERROR "HostedPlugin public seam must expose ProcessBlockView processing")
endif()
string(FIND "${implementation_source}" "bool HostedPlugin::process(const ProcessBlockView& block) noexcept" deep_process_position)
if(deep_process_position EQUAL -1)
    message(FATAL_ERROR "HostedPlugin must own the deep ProcessBlockView implementation")
endif()

message(STATUS "R0-2 HostedPlugin deep seam is protocol-neutral and independent of the Single adapter")
