if(NOT DEFINED RACK_PROTOCOL OR NOT DEFINED RACK_SOURCE)
    message(FATAL_ERROR "RACK_PROTOCOL and RACK_SOURCE are required")
endif()

file(READ "${RACK_PROTOCOL}" protocol)
file(READ "${RACK_SOURCE}" source)

if(protocol MATCHES "#include[ \t]+\"common/protocol\\.hpp\"")
    message(FATAL_ERROR "Rack protocol must not depend on the Single protocol")
endif()
if(NOT protocol MATCHES "kRackProtocolVersion = [1-9][0-9]*")
    message(FATAL_ERROR "Rack protocol must have its own explicit nonzero version")
endif()

# R1-1's enduring contract is ordered serial HostedPlugin processing. Later
# tickets may replace fixed A/B statements with an immutable ordered generation,
# but every active slot must consume current and publish the next serial buffer.
if(NOT source MATCHES "initial.slots\\[0\\].*kRackSlotIdA")
    message(FATAL_ERROR "initial Rack generation must begin with stable slot A")
endif()
if(NOT source MATCHES "initial.slots\\[1\\].*kRackSlotIdB")
    message(FATAL_ERROR "initial Rack generation must preserve A then B order")
endif()
if(NOT source MATCHES "ProcessBlockView block\\{current, next_output")
    message(FATAL_ERROR "Rack DSP must process each active generation slot from current into next output")
endif()
if(NOT source MATCHES "slot.plugin->process\\(block\\)")
    message(FATAL_ERROR "Rack DSP must invoke HostedPlugin through the protocol-neutral block seam")
endif()
if(NOT source MATCHES "current = next_output")
    message(FATAL_ERROR "Rack DSP must feed each successful slot output into the next serial slot")
endif()
if(NOT source MATCHES "std::array<std::array<float, kMaxFrames>, kMaxChannels> ping")
    message(FATAL_ERROR "Rack DSP must own preallocated ping storage")
endif()
if(NOT source MATCHES "std::array<std::array<float, kMaxFrames>, kMaxChannels> pong")
    message(FATAL_ERROR "Rack DSP must own preallocated pong storage")
endif()

foreach(forbidden IN ITEMS "std::vector" "push_back" "resize(" "new " "malloc(" "calloc(" "realloc(" "make_unique" "make_shared")
    string(FIND "${source}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Rack source contains allocation-capable token: ${forbidden}")
    endif()
endforeach()

message(STATUS "R1-1 Rack protocol isolation and serial DSP allocation contract passed")
