file(READ "${RACK_PROTOCOL}" PROTOCOL_TEXT)
file(READ "${RACK_SOURCE}" SOURCE_TEXT)

string(FIND "${PROTOCOL_TEXT}" "#include \"common/protocol.hpp\"" SINGLE_PROTOCOL_INCLUDE)
if(NOT SINGLE_PROTOCOL_INCLUDE EQUAL -1)
    message(FATAL_ERROR "Rack protocol must remain independent from Single common/protocol.hpp")
endif()

if(NOT PROTOCOL_TEXT MATCHES "kRackProtocolVersion = [2-9][0-9]*")
    message(FATAL_ERROR "Rack transport must remain independently versioned at or beyond R1-2")
endif()
if(NOT PROTOCOL_TEXT MATCHES "kRackBypassSlotA")
    message(FATAL_ERROR "R1-2 Rack protocol must define fixed slot A bypass bit")
endif()
if(NOT PROTOCOL_TEXT MATCHES "kRackBypassSlotB")
    message(FATAL_ERROR "R1-2 Rack protocol must define fixed slot B bypass bit")
endif()
if(NOT PROTOCOL_TEXT MATCHES "bypass_mask")
    message(FATAL_ERROR "R1-2 Rack protocol must carry per-block bypass state")
endif()
if(NOT PROTOCOL_TEXT MATCHES "std::uint32_t total_latency_samples")
    message(FATAL_ERROR "R1-2 Rack protocol must publish unsigned coherent total latency")
endif()

# Latency is now snapped into each immutable generation slot rather than queried
# from hard-coded A/B statements on every block. The enduring R1-2 invariant is
# that active generation slots contribute their captured latency and bypassed
# A/B identities contribute zero.
if(NOT SOURCE_TEXT MATCHES "latency_samples = 0")
    message(FATAL_ERROR "Rack generation slot must carry coherent latency metadata")
endif()
if(NOT SOURCE_TEXT MATCHES "plugin->latency_samples\\(\\)")
    message(FATAL_ERROR "Rack control/generation build must snapshot HostedPlugin latency")
endif()
string(FIND "${SOURCE_TEXT}" "total_latency += slot.latency_samples" ACTIVE_LATENCY_SUM)
if(ACTIVE_LATENCY_SUM EQUAL -1)
    message(FATAL_ERROR "Rack DSP must sum active generation-slot latency")
endif()
if(NOT SOURCE_TEXT MATCHES "kRackBypassSlotA")
    message(FATAL_ERROR "Rack DSP must preserve slot A bypass semantics")
endif()
if(NOT SOURCE_TEXT MATCHES "kRackBypassSlotB")
    message(FATAL_ERROR "Rack DSP must preserve slot B bypass semantics")
endif()
if(NOT SOURCE_TEXT MATCHES "region.output\\[ch\\]\\[frame\\] = region.input\\[ch\\]\\[frame\\]")
    message(FATAL_ERROR "Rack active-slot failure must explicitly publish original dry input")
endif()
if(NOT SOURCE_TEXT MATCHES "copy_original_dry\\(\\*endpoint.region, channels, frames\\)")
    message(FATAL_ERROR "Rack active-slot failure paths must share the original-dry publisher")
endif()

foreach(FORBIDDEN "std::vector" "std::make_unique" "std::make_shared" "new " "malloc(" "calloc(" "realloc(")
    string(FIND "${SOURCE_TEXT}" "${FORBIDDEN}" FOUND_TOKEN)
    if(NOT FOUND_TOKEN EQUAL -1)
        message(FATAL_ERROR "project-owned allocation token '${FORBIDDEN}' found in Rack source")
    endif()
endforeach()
