file(READ "${RACK_PROTOCOL}" PROTOCOL_TEXT)
file(READ "${RACK_SOURCE}" SOURCE_TEXT)

string(FIND "${PROTOCOL_TEXT}" "#include \"common/protocol.hpp\"" SINGLE_PROTOCOL_INCLUDE)
if(NOT SINGLE_PROTOCOL_INCLUDE EQUAL -1)
    message(FATAL_ERROR "Rack protocol must remain independent from Single common/protocol.hpp")
endif()

if(NOT PROTOCOL_TEXT MATCHES "kRackProtocolVersion = 2")
    message(FATAL_ERROR "R1-2 must version the changed Rack transport contract")
endif()
if(NOT PROTOCOL_TEXT MATCHES "kRackBypassSlotA")
    message(FATAL_ERROR "R1-2 Rack protocol must define fixed slot A bypass bit")
endif()
if(NOT PROTOCOL_TEXT MATCHES "kRackBypassSlotB")
    message(FATAL_ERROR "R1-2 Rack protocol must define fixed slot B bypass bit")
endif()
if(NOT PROTOCOL_TEXT MATCHES "bypass_mask")
    message(FATAL_ERROR "R1-2 Rack protocol must carry per-block bypass state")
endif()
if(NOT PROTOCOL_TEXT MATCHES "std::uint32_t total_latency_samples")
    message(FATAL_ERROR "R1-2 Rack protocol must publish unsigned coherent total latency")
endif()

if(NOT SOURCE_TEXT MATCHES "plugin_a.latency_samples\\(\\)")
    message(FATAL_ERROR "Rack helper must query Gain A HostedPlugin latency")
endif()
if(NOT SOURCE_TEXT MATCHES "plugin_b.latency_samples\\(\\)")
    message(FATAL_ERROR "Rack helper must query Gain B HostedPlugin latency")
endif()
if(NOT SOURCE_TEXT MATCHES "kRackBypassSlotA")
    message(FATAL_ERROR "Rack DSP must consume slot A bypass state")
endif()
if(NOT SOURCE_TEXT MATCHES "kRackBypassSlotB")
    message(FATAL_ERROR "Rack DSP must consume slot B bypass state")
endif()
if(NOT SOURCE_TEXT MATCHES "region.output\\[ch\\]\\[frame\\] = region.input\\[ch\\]\\[frame\\]")
    message(FATAL_ERROR "Rack active-slot failure must explicitly publish original dry input")
endif()
if(NOT SOURCE_TEXT MATCHES "copy_original_dry\\(\\*endpoint.region, channels, frames\\)")
    message(FATAL_ERROR "Rack active-slot failure paths must share the original-dry publisher")
endif()

foreach(FORBIDDEN "std::vector" "std::make_unique" "std::make_shared" "new " "malloc(" "calloc(" "realloc(")
    string(FIND "${SOURCE_TEXT}" "${FORBIDDEN}" FOUND_TOKEN)
    if(NOT FOUND_TOKEN EQUAL -1)
        message(FATAL_ERROR "project-owned allocation token '${FORBIDDEN}' found in Rack source")
    endif()
endforeach()
